# Generated by Django 3.0.7 on 2020-06-24 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='suit',
            new_name='SUIT_CHOICES',
        ),
    ]
