# Generated by Django 3.0.7 on 2020-06-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20200624_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='SUIT_CHOICES',
        ),
        migrations.AddField(
            model_name='card',
            name='suit',
            field=models.CharField(choices=[('diamonds', 'Diamonds'), ('clubs', 'Clubs'), ('spades', 'Spades'), ('hearts', 'Hearts')], default='Diamonds', max_length=50),
            preserve_default=False,
        ),
    ]
